---
# tasks file for vector-role

- name: Vector Install
  include_tasks: install.yml
  tags:
    - vector_install

- name: Vector Configure
  template:
    src: vector.yml.j2
    dest: vector.yml
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
  notify: start_vector
  tags:
    - vector_configure

- name: Vector Service
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: "644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  tags:
    - vector_service
