---
# handlers file for vector-role
- name: start_vector
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true
  when: 
    - ansible_virtualization_type != "docker"
    - ansible_virtualization_type != "podman"
  tags:
    - vector_start