---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: centos_8
    image: centos:8
    dockerfile: Dockerfile.j2
    run: >
      sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && 
      sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
    command: /usr/sbin/init
    privileged: true
  - name: ubuntu
    image: ubuntu:20.04
    dockerfile: Dockerfile.j2
    command: /sbin/init
    privileged: true
    env:
      DEBIAN_FRONTEND: "noninteractive" 
      TZ: "Etc/GMT+5"
  - name: centos_7
    image: centos:7
    dockerfile: Dockerfile.j2
    command: /usr/sbin/init
    privileged: true
provisioner:
  name: ansible
  options:
    vv: true
    D: true
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - destroy
    - create
    - converge
    - verify
    - cleanup
    - destroy
